# Generated by Django 5.0.3 on 2025-07-01 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participacao',
            old_name='Evento',
            new_name='evento_2',
        ),
    ]
