# Generated by Django 5.0.3 on 2025-06-20 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_1', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=13)),
            ],
        ),
    ]
